PUT http://localhost:3000/api/properties/single/1/status HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsInJvbGUiOiJob3N0IiwiaWF0IjoxNzgwMzUzMzU1LCJleHAiOjE3ODA0Mzk3NTV9.FcnMXO9y9EynJyNXQd82-S5nUTavU6T_v1ARaXfLtB4
Content-Type: application/json

{
    "statusId": 1
}