PATCH http://localhost:3000/api/properties/single/4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6Imhvc3QiLCJpYXQiOjE3NzcyNDc5NzYsImV4cCI6MTc3NzMzNDM3Nn0.HwWGZ6yb56KPHOTdE3oMSsOEtEFbZNNskx9jr3YttQM
Content-Type: application/json

{
    "statusId": 1,
    "rating": "",
    "propertyTypeId": 5,
    "ownerDescription": "Właściciel sigmiok"
}