version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: booking-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zwiq123
      POSTGRES_DB: booking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Node.js Application
  app:
    build: .
    container_name: booking-app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:zwiq123@db:5432/booking
      JWT_SECRET: booking
      GMAIL_NAME: bartoszgrobelny9@gmail.com
      GMAIL_PASSWORD: zoyehacjvzzjfwdz
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public/uploads:/app/public/uploads
    command: >
      sh -c "sleep 5 &&
             npx prisma migrate deploy &&
             npx prisma db seed &&
             npm run dev"

volumes:
  postgres_data:
