GET http://localhost:3000/api/properties/single/4/host HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6Imhvc3QiLCJpYXQiOjE3NzczNTgwMzQsImV4cCI6MTc3NzQ0NDQzNH0.Fq5lXGnYQnrr4bdniFj5rNt1_n1XVdPmxo9YvWwNIrk