POST http://localhost:3000/api/properties HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6Imhvc3QiLCJpYXQiOjE3NzcxNTc5ODMsImV4cCI6MTc3NzI0NDM4M30.3smMligNEUikxS7u0Cyp9XZ28xtdc7C-nVX2Fdv4Dec
Content-Type: application/json

{
    "name": "propertyName",
    "address": {
        "latitude": 50.50,
        "longitude": -20.20,
        "country": "Poland",
        "state": "malopolskie",
        "city": "Kraków",
        "postalCode": "123-12",
        "street": "Adolfa Nowaczynskiego 2"
    },
    "rating": 5,
    "type": 1,
    "propertyDescription": "Hotel elo",
    "ownerDescription": "Właściciel sigma",
    "surroundingsDescription": "Okolica spoko",
    "amenities": [51, 49, 32, 35],
    "spokenLanguages": [1, 2],
    "images": [
        {"isMain": true, "path": "/uploads/images-1777162646767-2125676.jpg"},
        {"path": "/uploads/images-1777162646767-2125676.jpg"}
    ],
    "rooms": [
        {
            "name": "pokój elo",
            "capacity": 3,
            "area": 140,
            "smokingAllowed": true,
            "bathroomPrivate": false,
            "beds": [
                {"type": 1, "count": 2},
                {"type": 2}
            ],
            "amenities": [1, 12, 24, 36],
            "pricing": {
                "price": 100.99
            },
            "count": 5
        }
    ]
}